{-# LANGUAGE DataKinds #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}

-- | Generated by jshark-bindgen from test/fixtures/jshark-bindgen/ms.d.ts.
-- FFI names assume the library is on the JS global object (ms).
module BindgenMs
  ( ms
  , ms2
  )
where

import JShark.Api
import JShark.Api.Rec (Rec (..), (<:))

ms ::
  Expr f ('String)
  -> EffectSyntax f (Expr f ('Number))
ms value = bindExpr $ ffi "ms" (arg value <: RecNil)

ms2 ::
  Expr f ('Number)
  -> EffectSyntax f (Expr f ('String))
ms2 value = bindExpr $ ffi "ms" (arg value <: RecNil)

