{-# LANGUAGE DataKinds #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}

-- | Generated by jshark-bindgen from test/fixtures/jshark-bindgen/toy.js.
-- FFI names assume the library is on the JS global object.
module BindgenJs
  ( greet
  , add
  , log_
  )
where

import JShark.Api
import JShark.Api.Rec (Rec (..), (<:))

greet ::
  Expr f ('String)
  -> EffectSyntax f (Expr f ('String))
greet name = bindExpr $ ffi "greet" (arg name <: RecNil)

add ::
  Expr f ('Number)
  -> Expr f ('Number)
  -> EffectSyntax f (Expr f ('Number))
add a b = bindExpr $ ffi "add" (arg a <: arg b <: RecNil)

log_ ::
  Expr f ('String)
  -> EffectSyntax f ()
log_ msg = toSyntax_ $ ffi "log" (arg msg <: RecNil)

