{-# LANGUAGE DataKinds #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}

-- | Generated by jshark-bindgen from test/fixtures/jshark-bindgen/toy.d.ts.
-- FFI names assume the library is on the JS global object (toy).
module BindgenToy
  ( Size
  , Widget
  , version
  , greet
  , add
  , log_
  , clamp
  , newWidget
  , resize
  , size
  )
where

import JShark.Api
import JShark.Api.Rec (Rec (..), (<:))

-- | JS @toy.Size@.
data Size

-- | JS @toy.Widget@.
data Widget

type instance Field Size "width" = 'Number

type instance Field Size "height" = 'Number

type instance Field Widget "id" = 'String

type instance Field Widget "width" = 'Number

version :: EffectSyntax f (Expr f ('String))
version = bindExpr $ ffiExpr "toy.VERSION" RecNil

greet ::
  Expr f ('String)
  -> EffectSyntax f (Expr f ('String))
greet name = bindExpr $ ffi "toy.greet" (arg name <: RecNil)

add ::
  Expr f ('Number)
  -> Expr f ('Number)
  -> EffectSyntax f (Expr f ('Number))
add a b = bindExpr $ ffi "toy.add" (arg a <: arg b <: RecNil)

log_ ::
  Expr f ('String)
  -> EffectSyntax f ()
log_ msg = toSyntax_ $ ffi "toy.log" (arg msg <: RecNil)

clamp ::
  Expr f ('Number)
  -> Expr f ('Number)
  -> Expr f ('Number)
  -> EffectSyntax f (Expr f ('Number))
clamp n lo hi = bindExpr $ ffi "toy.util.clamp" (arg n <: arg lo <: arg hi <: RecNil)

newWidget ::
  Expr f ('String)
  -> EffectSyntax f (Effect f ('MutableObject Widget))
newWidget id_ = hold $ ffi "new toy.Widget" (arg id_ <: RecNil)

resize ::
  Effect f ('MutableObject Widget)
  -> Expr f ('Number)
  -> Expr f ('Number)
  -> EffectSyntax f ()
resize self w h = toSyntax_ $ callMethod self "resize" (arg w <: arg h <: RecNil)

size ::
  Effect f ('MutableObject Widget)
  -> EffectSyntax f (Effect f ('MutableObject Size))
size self = hold $ callMethod self "size" RecNil
