{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}

-- | Print 'ModuleIr' as a JShark FFI wrapper module.
module JShark.Bindgen.Emit
  ( emitModule
  , hsTypeName
  , hsVarName
  )
where

import Data.Char (isAlpha, isAlphaNum, toLower, toUpper)
import Data.List (nub, sort, (\\))
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import qualified Data.Text as T
import JShark.Bindgen.Ir

emitModule :: ModuleIr -> Text
emitModule ir =
  let
    plan = planModuleNames ir
   in
    T.unlines $
      header ir
        <> exportBlock plan
        <> whereLine
        <> imports ir
        <> phantoms ir
        <> fieldInsts ir
        <> enumMembers ir plan
        <> constBinds ir plan
        <> funBinds ir plan
        <> classBinds ir plan

-- Name planning ---------------------------------------------------------

data FunKey = FunKey
  { fkOwner :: Text
  , fkName :: Text
  , fkCtor :: Bool
  , fkStatic :: Bool
  }
  deriving (Eq, Ord, Show)

data NamePlan = NamePlan
  { npExports :: [Text]
  , npFun :: Map FunKey Text
  , npConst :: Map Text Text
  , npEnumMember :: Map (Text, Text) Text
  }

planModuleNames :: ModuleIr -> NamePlan
planModuleNames ir =
  let
    slots =
      (if moduleUsesUnknown ir then [SlotType "JsUnknown"] else [])
        <> fmap (SlotType . hsTypeName . clName) (irClasses ir)
        <> fmap (SlotType . hsTypeName . enName) (irEnums ir)
        <> fmap (SlotConst . cnName) (irConsts ir)
        <> concatMap enumMemberSlots (irEnums ir)
        <> fmap (\fn -> SlotFun (FunKey T.empty (fnName fn) False False)) (irFuns ir)
        <> concatMap classFunSlots (irClasses ir)
    rawNames = fmap slotRaw slots
    finalNames = globalUnique rawNames
    named = zip slots finalNames
    funMap =
      Map.fromList
        [ (k, n)
        | (SlotFun k, n) <- named
        ]
    constMap =
      Map.fromList
        [ (cn, n)
        | (SlotConst cn, n) <- named
        ]
    enumMap =
      Map.fromList
        [ ((en, mem), n)
        | (SlotEnum en mem, n) <- named
        ]
   in
    NamePlan
      { npExports = finalNames
      , npFun = funMap
      , npConst = constMap
      , npEnumMember = enumMap
      }

data Slot
  = SlotType Text
  | SlotConst Text
  | SlotEnum Text Text
  | SlotFun FunKey

slotRaw :: Slot -> Text
slotRaw = \case
  SlotType n -> n
  SlotConst cn -> hsVarName cn
  SlotEnum en mem -> enumMemberName en mem
  SlotFun (FunKey _ n isCtor _) -> hsFunName isCtor n

enumMemberSlots :: EnumDecl -> [Slot]
enumMemberSlots e =
  [ SlotEnum (enName e) (emName m)
  | m <- enMembers e
  ]

classFunSlots :: ClassDecl -> [Slot]
classFunSlots c =
  [ SlotFun (FunKey (clName c) (fnName f) True False) | f <- clCtors c
  ]
    <> [ SlotFun (FunKey (clName c) (fnName f) False (fnStatic f))
       | f <- clMethods c
       ]

globalUnique :: [Text] -> [Text]
globalUnique = go []
 where
  go _ [] = []
  go seen (n : ns) =
    let
      n' = pick n (1 :: Int) seen
     in
      n' : go (n' : seen) ns
  pick n k seen =
    let
      cand = if k == 1 then n else n <> T.pack (show k)
     in
      if cand `elem` seen then pick n (k + 1) seen else cand

lookupFun :: NamePlan -> FunKey -> Text
lookupFun plan k =
  Map.findWithDefault (hsFunName (fkCtor k) (fkName k)) k (npFun plan)

-- Header / exports ------------------------------------------------------

header :: ModuleIr -> [Text]
header ir =
  [ "{-# LANGUAGE DataKinds #-}"
  , "{-# LANGUAGE KindSignatures #-}"
  , "{-# LANGUAGE OverloadedStrings #-}"
  , "{-# LANGUAGE TypeFamilies #-}"
  , ""
  , "-- | Generated by jshark-bindgen from "
      <> irSource ir
      <> "."
  , "-- FFI names assume the library is on the JS global object"
      <> prefixNote ir
      <> "."
  , "module " <> irModule ir
  ]

prefixNote :: ModuleIr -> Text
prefixNote ir
  | T.null (irPrefix ir) = T.empty
  | otherwise = " (" <> irPrefix ir <> ")"

exportBlock :: NamePlan -> [Text]
exportBlock plan =
  case npExports plan of
    [] -> ["  ()"]
    n : ns ->
      "  ( " <> n
        : fmap ("  , " <>) ns
        ++ ["  )"]

whereLine :: [Text]
whereLine = ["where", ""]

imports :: ModuleIr -> [Text]
imports ir =
  [ "import JShark.Api"
  , "import JShark.Api.Rec (Rec (..), (<:))"
  ]
    <> ["import JShark.Promise (Promise)" | moduleUsesPromise ir]
    <> [""]

-- Phantoms --------------------------------------------------------------

phantoms :: ModuleIr -> [Text]
phantoms ir =
  ( if moduleUsesUnknown ir
      then
        [ "-- | Opaque JS value bindgen could not map onto a 'Universe'."
        , "data JsUnknown"
        , ""
        ]
      else []
  )
    <> concatMap phantomClass (irClasses ir)
    <> concatMap phantomEnum (irEnums ir)
    <> concatMap phantomNamed (extraNamedTypes ir)

phantomClass :: ClassDecl -> [Text]
phantomClass c =
  [ "-- | JS @" <> clFfi c <> "@."
  , "data " <> hsTypeName (clName c)
  , ""
  ]

phantomEnum :: EnumDecl -> [Text]
phantomEnum e =
  [ "-- | JS enum @" <> enName e <> "@."
  , "data " <> hsTypeName (enName e)
  , ""
  ]

phantomNamed :: Text -> [Text]
phantomNamed n =
  [ "-- | JS @" <> n <> "@ (referenced type)."
  , "data " <> hsTypeName n
  , ""
  ]

extraNamedTypes :: ModuleIr -> [Text]
extraNamedTypes ir =
  let
    declared =
      nub $
        fmap clName (irClasses ir)
          <> fmap enName (irEnums ir)
    refs = nub (sort (referencedNamedTypes ir))
   in
    refs \\ declared

referencedNamedTypes :: ModuleIr -> [Text]
referencedNamedTypes ir =
  concatMap tyNamed (moduleTypes ir)

moduleTypes :: ModuleIr -> [Ty]
moduleTypes ir =
  concat
    [ fmap cnTy (irConsts ir)
    , concatMap classTypes (irClasses ir)
    , concatMap funTypes (irFuns ir)
    ]
 where
  classTypes c =
    fmap prTy (clProps c)
      <> concatMap funTypes (clCtors c)
      <> concatMap funTypes (clMethods c)
  funTypes f = fnRet f : fmap pTy (fnParams f)

tyNamed :: Ty -> [Text]
tyNamed = \case
  TyNamed n -> [n]
  TyArray t -> tyNamed t
  TyOption t -> tyNamed t
  TySet t -> tyNamed t
  TyPromise t -> tyNamed t
  TyMap k v -> tyNamed k <> tyNamed v
  TyFun as r -> concatMap tyNamed as <> tyNamed r
  _ -> []

-- Fields / enums --------------------------------------------------------

fieldInsts :: ModuleIr -> [Text]
fieldInsts ir =
  concatMap classFields (irClasses ir)

classFields :: ClassDecl -> [Text]
classFields c =
  concatMap (fieldInst (clName c)) (clProps c)

fieldInst :: Text -> Prop -> [Text]
fieldInst cls p
  | validSymbol (prName p) =
      [ "type instance Field "
          <> hsTypeName cls
          <> " \""
          <> prName p
          <> "\" = "
          <> emitUniverse (prTy p)
      , ""
      ]
  | otherwise = []

enumMembers :: ModuleIr -> NamePlan -> [Text]
enumMembers ir plan =
  concatMap (emitEnum plan) (irEnums ir)

emitEnum :: NamePlan -> EnumDecl -> [Text]
emitEnum plan e =
  concatMap (emitEnumMember plan e) (enMembers e)

emitEnumMember :: NamePlan -> EnumDecl -> EnumMember -> [Text]
emitEnumMember plan e m =
  let
    v =
      Map.findWithDefault
        (enumMemberName (enName e) (emName m))
        (enName e, emName m)
        (npEnumMember plan)
    (ty, lit) = case (emNumeric m, emValue m) of
      (True, Just n) -> ("'Number", "number " <> n)
      (_, Just s) -> ("'String", "string " <> showT s)
      _ -> ("'String", "string " <> showT (emName m))
   in
    sigLines v [] ("Expr f " <> ty) <> [v <> " = " <> lit, ""]

-- Consts / funs ---------------------------------------------------------

constBinds :: ModuleIr -> NamePlan -> [Text]
constBinds ir plan =
  concatMap (emitConst plan) (irConsts ir)

emitConst :: NamePlan -> ConstDecl -> [Text]
emitConst plan c =
  let
    v = Map.findWithDefault (hsVarName (cnName c)) (cnName c) (npConst plan)
    ret = wrapRet (cnTy c)
    body = applyRet (cnTy c) ("ffiExpr " <> showT (cnFfi c) <> " RecNil")
   in
    sigLines v [] ret <> [v <> " = " <> body, ""]

funBinds :: ModuleIr -> NamePlan -> [Text]
funBinds ir plan =
  concatMap (emitTopFun plan) (irFuns ir)

emitTopFun :: NamePlan -> Fun -> [Text]
emitTopFun plan f =
  let
    key = FunKey T.empty (fnName f) False False
    name = lookupFun plan key
   in
    emitFun plan Nothing name f

classBinds :: ModuleIr -> NamePlan -> [Text]
classBinds ir plan =
  concatMap (emitClass plan) (irClasses ir)

emitClass :: NamePlan -> ClassDecl -> [Text]
emitClass plan c =
  concatMap (emitClassFun plan c True) (clCtors c)
    <> concatMap (emitClassFun plan c False) (clMethods c)

emitClassFun :: NamePlan -> ClassDecl -> Bool -> Fun -> [Text]
emitClassFun plan c isCtor f =
  let
    key = FunKey (clName c) (fnName f) isCtor (fnStatic f)
    name = lookupFun plan key
   in
    emitFun plan (Just c) name f

emitFun :: NamePlan -> Maybe ClassDecl -> Text -> Fun -> [Text]
emitFun _plan owner name f =
  let
    isCtor = fnIsCtor f
    params = requiredParams (fnParams f)
    paramNames = uniqueParamNames params
    selfTy =
      case owner of
        Just c
          | not isCtor && not (fnStatic f) ->
              Just ("Effect f ('MutableObject " <> hsTypeName (clName c) <> ")")
        _ -> Nothing
    argTys =
      maybe id (:) selfTy (fmap (wrapArg . pTy) params)
    ret = wrapRet (fnRet f)
    hsArgs =
      maybe id (:) (selfTy >> Just "self") (fmap snd paramNames)
    call = emitCall owner f paramNames
    body = applyRet (fnRet f) call
    lhs =
      if null hsArgs
        then name <> " = " <> body
        else name <> " " <> T.unwords hsArgs <> " = " <> body
   in
    sigLines name argTys ret <> [lhs, ""]

requiredParams :: [Param] -> [Param]
requiredParams = filter (not . pOptional)

uniqueParamNames :: [Param] -> [(Param, Text)]
uniqueParamNames = go []
 where
  go _ [] = []
  go seen (p : ps) =
    let
      base = hsVarName (pName p)
      n' = pick base (1 :: Int) seen
     in
      (p, n') : go (n' : seen) ps
  pick n k seen =
    let
      cand = if k == 1 then n else n <> T.pack (show k)
     in
      if cand `elem` seen then pick n (k + 1) seen else cand

emitCall :: Maybe ClassDecl -> Fun -> [(Param, Text)] -> Text
emitCall owner f paramNames
  | fnIsCtor f =
      "ffi " <> showT ("new " <> fnFfi f) <> " " <> recArgs paramNames
  | Just c <- owner
  , fnStatic f =
      "ffi "
        <> showT (clFfi c <> "." <> fnName f)
        <> " "
        <> recArgs paramNames
  | Just _ <- owner =
      "callMethod self "
        <> showT (fnName f)
        <> " "
        <> recArgs paramNames
  | otherwise =
      "ffi " <> showT (fnFfi f) <> " " <> recArgs paramNames

recArgs :: [(Param, Text)] -> Text
recArgs [] = "RecNil"
recArgs pns =
  let
    bits = fmap recArg pns
   in
    "(" <> T.intercalate " <: " bits <> " <: RecNil)"
 where
  recArg (p, n)
    | isHandle (pTy p) = "ArgEffect " <> n
    | otherwise = "arg " <> n

wrapArg :: Ty -> Text
wrapArg t
  | isHandle t = "Effect f (" <> emitUniverse t <> ")"
  | otherwise = "Expr f (" <> emitUniverse t <> ")"

wrapRet :: Ty -> Text
wrapRet t
  | isUnit t = "EffectSyntax f ()"
  | isHandle t = "EffectSyntax f (Effect f (" <> emitUniverse t <> "))"
  | otherwise = "EffectSyntax f (Expr f (" <> emitUniverse t <> "))"

applyRet :: Ty -> Text -> Text
applyRet t call
  | isUnit t = "toSyntax_ $ " <> call
  | isOptionHandle t =
      "hold $ Bind ("
        <> call
        <> ") (\\x -> Lift (unsafeNullable (Var x)))"
  | isHandle t = "hold $ " <> call
  | isOptionPrim t = "fmap unsafeNullable (bindExpr $ " <> call <> ")"
  | otherwise = "bindExpr $ " <> call

isUnit :: Ty -> Bool
isUnit TyUnit = True
isUnit _ = False

isHandle :: Ty -> Bool
isHandle = \case
  TyNamed _ -> True
  TyUnknown _ -> True
  TyPromise _ -> True
  TyArray t -> isHandle t
  TyOption t -> isHandle t
  TyMap _ _ -> True
  TySet _ -> True
  TyUint8Array -> False
  _ -> False

isOptionHandle :: Ty -> Bool
isOptionHandle (TyOption t) = isHandle t
isOptionHandle _ = False

isOptionPrim :: Ty -> Bool
isOptionPrim (TyOption t) = not (isHandle t) && not (isUnit t)
isOptionPrim _ = False

emitUniverse :: Ty -> Text
emitUniverse = \case
  TyNumber -> "'Number"
  TyBigInt -> "'BigInt"
  TyString -> "'String"
  TyBool -> "'Bool"
  TyUnit -> "'Unit"
  TyUint8Array -> "'Uint8Array"
  TyArray t -> "'Array (" <> emitUniverse t <> ")"
  TyOption t -> "'Option (" <> emitUniverse t <> ")"
  TyMap k v ->
    "'Map (" <> emitUniverse k <> ") (" <> emitUniverse v <> ")"
  TySet t -> "'Set (" <> emitUniverse t <> ")"
  TyPromise t ->
    "'MutableObject (Promise (" <> emitUniverse t <> "))"
  TyFun [a] r ->
    "'Function (" <> emitUniverse a <> ") (" <> emitUniverse r <> ")"
  TyFun as r ->
    "'Fn '["
      <> T.intercalate ", " (fmap emitUniverse as)
      <> "] ("
      <> emitUniverse r
      <> ")"
  TyNamed n -> "'MutableObject " <> hsTypeName n
  TyUnknown _ -> "'MutableObject JsUnknown"

-- Names -----------------------------------------------------------------

hsFunName :: Bool -> Text -> Text
hsFunName isCtor n
  | isCtor = hsVarName ("new" <> capitalize n)
  | otherwise = hsVarName n

enumMemberName :: Text -> Text -> Text
enumMemberName en mem = hsVarName (en <> mem)

hsTypeName :: Text -> Text
hsTypeName raw =
  let
    n = sanitizeType (dropNs raw)
   in
    if n `elem` reservedTypes then "Js" <> n else n

hsVarName :: Text -> Text
hsVarName raw =
  let
    n = sanitizeVar (dropNs raw)
   in
    if n `elem` reservedVars then n <> "_" else n

allCapsLower :: Text -> Maybe Text
allCapsLower t
  | not (T.null t) && T.all (\c -> not (isAlpha c) || c == toUpper c) t =
      Just (T.toLower t)
  | otherwise = Nothing

dropNs :: Text -> Text
dropNs t = case T.breakOnEnd "." t of
  ("", x) -> x
  (_, x) | T.null x -> t
  (_, x) -> x

sanitizeType :: Text -> Text
sanitizeType t =
  let
    parts = identParts t
    merged = T.concat (fmap capitalize parts)
   in
    if T.null merged then "JsVal" else ensureUpper merged

sanitizeVar :: Text -> Text
sanitizeVar t =
  let
    parts = identParts t
    merged = case parts of
      [] -> "jsVal"
      [p] | Just low <- allCapsLower p -> low
      p : ps -> lowerFirst p <> T.concat (fmap capitalize ps)
   in
    if T.null merged then "jsVal" else ensureLower merged

identParts :: Text -> [Text]
identParts =
  filter (not . T.null)
    . T.split (\c -> not (isAlphaNum c) && c /= '_')

ensureUpper :: Text -> Text
ensureUpper t = case T.uncons t of
  Just (c, rest) | isAlpha c -> T.cons (toUpper c) rest
  Just _ -> "Js" <> t
  Nothing -> "JsVal"

ensureLower :: Text -> Text
ensureLower t = case T.uncons t of
  Just (c, rest) | isAlpha c -> T.cons (toLower c) rest
  Just _ -> "js" <> t
  Nothing -> "jsVal"

capitalize :: Text -> Text
capitalize t = case T.uncons t of
  Just (c, rest) -> T.cons (toUpper c) rest
  Nothing -> t

lowerFirst :: Text -> Text
lowerFirst t = case T.uncons t of
  Just (c, rest) -> T.cons (toLower c) rest
  Nothing -> t

validSymbol :: Text -> Bool
validSymbol t = case T.uncons t of
  Just (c, rest) ->
    isAlpha c && T.all (\x -> isAlphaNum x || x == '_') rest
  Nothing -> False

reservedTypes :: [Text]
reservedTypes =
  [ "String"
  , "Number"
  , "Bool"
  , "Array"
  , "Object"
  , "Function"
  , "Unit"
  , "IO"
  , "Maybe"
  , "Either"
  , "Int"
  , "Type"
  ]

reservedVars :: [Text]
reservedVars =
  [ "as"
  , "case"
  , "class"
  , "data"
  , "default"
  , "deriving"
  , "do"
  , "else"
  , "hiding"
  , "if"
  , "import"
  , "in"
  , "infix"
  , "infixl"
  , "infixr"
  , "instance"
  , "let"
  , "module"
  , "newtype"
  , "of"
  , "qualified"
  , "then"
  , "type"
  , "where"
  , "forall"
  , "export"
  , "foreign"
  , "mdo"
  , "rec"
  , "proc"
  , "pattern"
  , "id"
  , "map"
  , "filter"
  , "error"
  , "log"
  , "not"
  , "and"
  , "or"
  , "div"
  , "mod"
  , "min"
  , "max"
  , "return"
  , "fail"
  , "fmap"
  , "pure"
  , "seq"
  , "show"
  , "print"
  , "const"
  , "flip"
  , "fst"
  , "snd"
  , "head"
  , "tail"
  , "null"
  , "length"
  , "bind"
  , "arg"
  , "expr"
  , "var"
  , "hold"
  , "done"
  ]

sigLines :: Text -> [Text] -> Text -> [Text]
sigLines name [] ret = [name <> " :: " <> ret]
sigLines name (t : ts) ret =
  (name <> " ::")
    : ("  " <> t)
    : fmap ("  -> " <>) (ts <> [ret])

showT :: Text -> Text
showT t = T.pack (show (T.unpack t))
