{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}

-- | Print 'ModuleIr' as a JShark FFI wrapper module.
module JShark.Bindgen.Emit (emitModule, hsTypeName, hsVarName) where

import Data.Char (isAlpha, isAlphaNum, toLower, toUpper)
import Data.List (find, nub, sort)
import qualified Data.Map.Strict as Map
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import JShark.Bindgen.Ir

-- | A declaration that takes an exported Haskell name.
data Slot
  = SType Text
  | SConst Text
  | SEnum Text Text
  | -- | Owner class (empty at top level), name, ctor?, static?, overload.
    SFun Text Text Bool Bool Int
  deriving (Eq, Ord)

-- | Render a 'ModuleIr' as a complete JShark FFI module.
emitModule :: ModuleIr -> Text
emitModule ir =
  T.unlines $
    [ "{-# LANGUAGE DataKinds #-}"
    , "{-# LANGUAGE KindSignatures #-}"
    , "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# LANGUAGE TypeFamilies #-}"
    , ""
    , "-- | Generated by jshark-bindgen from " <> irSource ir <> "."
    , "-- FFI names assume the library is on the JS global object"
        <> (if T.null (irPrefix ir) then "" else " (" <> irPrefix ir <> ")")
        <> "."
    , "module " <> irModule ir
    ]
      <> exports
      <> ["where", "", "import JShark.Api"]
      <> ["import JShark.Promise (Promise)" | moduleUsesPromise ir]
      <> [""]
      <> concatMap phantom phantoms
      <> concat
        [ [ "type instance Field "
              <> hsTypeName (clName c)
              <> " \""
              <> prName p
              <> "\" = "
              <> emitUniverse (prTy p)
          , ""
          ]
        | c <- irClasses ir
        , p <- clProps c
        , validSymbol (prName p)
        ]
      <> concat [enumMember e m | e <- irEnums ir, m <- enMembers e]
      <> concatMap constDecl (irConsts ir)
      <> concat
        [emitFun Nothing (name (funSlot T.empty False False f)) f | f <- irFuns ir]
      <> concat
        [ emitFun (Just c) (name (funSlot (clName c) k (fnStatic f) f)) f
        | c <- irClasses ir
        , (k, f) <- classFuns c
        ]
 where
  classFuns c = map ((,) True) (clCtors c) <> map ((,) False) (clMethods c)
  funSlot owner ctor static f = SFun owner (fnName f) ctor static (fnOverload f)
  slots =
    [SType "JsUnknown" | moduleUsesUnknown ir]
      <> map (SType . hsTypeName . clName) (irClasses ir)
      <> map (SType . hsTypeName . enName) (irEnums ir)
      <> map (SConst . cnName) (irConsts ir)
      <> [SEnum (enName e) (emName m) | e <- irEnums ir, m <- enMembers e]
      <> map (funSlot T.empty False False) (irFuns ir)
      -- Constructors are planned as non-static.
      <> [ funSlot (clName c) k (not k && fnStatic f) f
         | c <- irClasses ir
         , (k, f) <- classFuns c
         ]
  names = uniques (map slotName slots)
  plan = Map.fromList (zip slots names)
  name s = Map.findWithDefault (slotName s) s plan
  exports = case names of
    [] -> ["  ()"]
    n : ns -> ("  ( " <> n) : map ("  , " <>) ns <> ["  )"]
  phantoms =
    [ ("Opaque JS value bindgen could not map onto a 'Universe'.", "JsUnknown")
    | moduleUsesUnknown ir
    ]
      <> [("JS @" <> clFfi c <> "@.", clName c) | c <- irClasses ir]
      <> [("JS enum @" <> enName e <> "@.", enName e) | e <- irEnums ir]
      <> [ ("JS @" <> n <> "@ (referenced type).", n)
         | n <- referenced
         , n `notElem` declared
         ]
  phantom (doc, n) = ["-- | " <> doc, "data " <> hsTypeName n, ""]
  declared = map clName (irClasses ir) <> map enName (irEnums ir)
  referenced =
    nub (sort [n | (_, ts) <- declTypes ir, t <- ts, TyNamed n <- tyAndChildren t])
  enumMember e m =
    decl (name (SEnum (enName e) (emName m))) [] ("Expr f " <> ty) [] lit
   where
    (ty, lit) = case (emNumeric m, emValue m) of
      (True, Just n) -> ("'Number", "number " <> n)
      (_, Just s) -> ("'String", "string " <> showT s)
      _ -> ("'String", "string " <> showT (emName m))
  constDecl c =
    decl (name (SConst (cnName c))) [] (wrapRet (cnTy c)) [] $
      applyRet (cnTy c) ("ffiExpr " <> showT (cnFfi c) <> " RecNil")

-- | The Haskell name a slot takes before 'uniques' disambiguates it.
slotName :: Slot -> Text
slotName = \case
  SType n -> n
  SConst n -> hsVarName n
  SEnum e m -> hsVarName (e <> m)
  SFun _ n ctor _ _ -> hsVarName (if ctor then "new" <> capitalize n else n)

-- | Make each name distinct by suffixing @2@, @3@, … on repeats.
uniques :: [Text] -> [Text]
uniques = go []
 where
  go _ [] = []
  go seen (n : ns) = c : go (c : seen) ns
   where
    c = fromMaybe n (find (`notElem` seen) candidates)
    candidates = n : [n <> T.pack (show k) | k <- [2 :: Int ..]]

-- | A wrapper for a function, constructor, or (static) method of @owner@.
emitFun :: Maybe ClassDecl -> Text -> Fun -> [Text]
emitFun owner name f =
  decl
    name
    (map fst self <> map (wrapArg . pTy) params)
    (wrapRet (fnRet f))
    (map snd self <> map snd args)
    (applyRet (fnRet f) (callee <> " " <> recArgs))
 where
  params = filter (not . pOptional) (fnParams f)
  args = zip params (uniques (map (hsVarName . pName) params))
  self =
    [ ("Effect f ('MutableObject " <> hsTypeName (clName c) <> ")", "self")
    | Just c <- [owner]
    , not (fnIsCtor f || fnStatic f)
    ]
  callee = case owner of
    _ | fnIsCtor f -> "ffi " <> showT ("new " <> fnFfi f)
    Just c | fnStatic f -> "ffi " <> showT (clFfi c <> "." <> fnName f)
    Just _ -> "callMethod self " <> showT (fnName f)
    Nothing -> "ffi " <> showT (fnFfi f)
  recArgs
    | null args = "RecNil"
    | otherwise = "(" <> T.intercalate " <: " (map recArg args) <> " <: RecNil)"
  -- A declared @T | null@ argument is a tagged 'Option' inside JShark;
  -- unwrap it to the native null/value the foreign API expects.
  recArg (p, n) = case pTy p of
    t@(TyOption _)
      | isHandle t -> "ArgEffect (unsafeOptionToNativeEffect " <> n <> ")"
      | otherwise -> "arg (unsafeOptionToNative " <> n <> ")"
    t | isHandle t -> "ArgEffect " <> n
    _ -> "arg " <> n

-- | A type signature (argument types, then result) and a one-line equation.
decl :: Text -> [Text] -> Text -> [Text] -> Text -> [Text]
decl name tys ret args body =
  sig tys <> [T.unwords (name : args) <> " = " <> body, ""]
 where
  sig [] = [name <> " :: " <> ret]
  sig (t : ts) = (name <> " ::") : ("  " <> t) : map ("  -> " <>) (ts <> [ret])

wrapArg :: Ty -> Text
wrapArg t =
  (if isHandle t then "Effect" else "Expr") <> " f (" <> emitUniverse t <> ")"

wrapRet :: Ty -> Text
wrapRet TyUnit = "EffectSyntax f ()"
wrapRet t = "EffectSyntax f (" <> wrapArg t <> ")"

applyRet :: Ty -> Text -> Text
applyRet t call = case t of
  TyUnit -> "toSyntax_ $ " <> call
  TyOption a | isHandle a -> "hold $ optionalEffect (" <> call <> ")"
  _ | isHandle t -> "hold $ " <> call
  TyOption a | a /= TyUnit -> "fmap unsafeNullable (bindExpr $ " <> call <> ")"
  _ -> "bindExpr $ " <> call

-- | Types passed around as effectful handles rather than pure expressions.
isHandle :: Ty -> Bool
isHandle = any handle . tyAndChildren
 where
  handle = \case
    TyNamed _ -> True
    TyUnknown _ -> True
    TyPromise _ -> True
    TyMap _ _ -> True
    TySet _ -> True
    _ -> False

emitUniverse :: Ty -> Text
emitUniverse = \case
  TyNumber -> "'Number"
  TyBigInt -> "'BigInt"
  TyString -> "'String"
  TyBool -> "'Bool"
  TyUnit -> "'Unit"
  TyUint8Array -> "'Uint8Array"
  TyArray t -> "'Array" <> args [t]
  TyOption t -> "'Option" <> args [t]
  TyMap k v -> "'Map" <> args [k, v]
  TySet t -> "'Set" <> args [t]
  TyPromise t -> "'MutableObject (Promise" <> args [t] <> ")"
  TyFun [a] r -> "'Function" <> args [a, r]
  TyFun as r -> "'Fn '[" <> T.intercalate ", " (map emitUniverse as) <> "]" <> args [r]
  TyNamed n -> "'MutableObject " <> hsTypeName n
  TyUnknown _ -> "'MutableObject JsUnknown"
 where
  args = foldMap (\t -> " (" <> emitUniverse t <> ")")

-- | Render a raw JS name as a valid Haskell type name, avoiding reserved types.
hsTypeName :: Text -> Text
hsTypeName raw = if n `elem` reservedTypes then "Js" <> n else n
 where
  n = sanitize "Js" capitalize (T.concat (map capitalize (identParts raw)))

-- | Render a raw JS name as a valid Haskell variable name, avoiding reserved words.
hsVarName :: Text -> Text
hsVarName raw = if n `elem` reservedVars then n <> "_" else n
 where
  n = sanitize "js" lowerFirst $ case identParts raw of
    [p] | T.all (\c -> not (isAlpha c) || c == toUpper c) p -> T.toLower p
    p : ps -> lowerFirst p <> T.concat (map capitalize ps)
    [] -> T.empty

-- | Alphanumeric runs of the last dot-separated segment of a JS name.
identParts :: Text -> [Text]
identParts t =
  filter (not . T.null) (T.split (\c -> not (isAlphaNum c) && c /= '_') lastSeg)
 where
  lastSeg = case snd (T.breakOnEnd "." t) of
    "" -> t
    s -> s

-- | Case a name's alphabetic first letter with @f@; otherwise prefix @pre@.
sanitize :: Text -> (Text -> Text) -> Text -> Text
sanitize pre f t = case T.uncons t of
  Just (c, _) | isAlpha c -> f t
  Just _ -> pre <> t
  Nothing -> pre <> "Val"

capitalize, lowerFirst :: Text -> Text
capitalize = onHead toUpper
lowerFirst = onHead toLower

onHead :: (Char -> Char) -> Text -> Text
onHead f t = maybe t (\(c, rest) -> T.cons (f c) rest) (T.uncons t)

validSymbol :: Text -> Bool
validSymbol t = case T.uncons t of
  Just (c, rest) -> isAlpha c && T.all (\x -> isAlphaNum x || x == '_') rest
  Nothing -> False

reservedTypes :: [Text]
reservedTypes =
  T.words "String Number Bool Array Object Function Unit IO Maybe Either Int Type"

reservedVars :: [Text]
reservedVars =
  T.words
    "as case class data default deriving do else hiding if import in infix \
    \infixl infixr instance let module newtype of qualified then type where \
    \forall export foreign mdo rec proc pattern id map filter error log not \
    \and or div mod min max return fail fmap pure seq show print const flip \
    \fst snd head tail null length bind arg expr var hold done"

showT :: Text -> Text
showT t = T.pack (show (T.unpack t))
