#!/usr/bin/env bash
# Format all Haskell sources across the monorepo packages.
#
# jshark-bindgen writes some of its test fixtures as Haskell modules, and
# the tests compare them byte for byte against a fresh run of the
# generator. Formatting those would break the suite, so anything carrying
# the generator's banner is left exactly as it was written.
set -euo pipefail

mapfile -t sources < <(find ./packages ./examples -name '*.hs' | sort)

to_format=()
for f in "${sources[@]}"; do
  if head -n 10 "$f" | grep -q 'Generated by jshark-bindgen'; then
    continue
  fi
  to_format+=("$f")
done

fourmolu -i "${to_format[@]}"
